### PR TITLE
Fixed installer script.

### PR DESCRIPTION
**Pull request by redactedontop**
Here ya go <3

### CODE REVIEW

**Comment by arithefirst** [comment]
Please do not try to make style changes to my code, thanks.

**Comment by arithefirst** [comment]
Also a Syu is not required here, as there is no need to update the entire system during the dotfiles install. If a user wants to do that, they can, but since it is not a necessity, they should not be forced to.

**Comment by redactedontop** [comment]
Hello @arithefirst. These are not style changes.
Your exit instruction exists on the first instalation. The parenthesis fix these.
I'm seriously losing my patience right here.

Thank you,
Alex <3

**Comment by arithefirst** [comment]
That issue was already fixed. Even if not, the 2 lines you changed should have solved that. Not 7. In addition, as I already mentioned, the -Syu flag is not necessary when installing the packages, as a full system update is not required there. But it's ok, I can tell you're new to Linux because you're cloning someone's dotfiles instead of writing your own.

**Comment by redactedontop** [comment]
Oh sorry, my bad. Zed auto-formatted it.
Also, I'm not new to Linux. Just found your dots, thought they looked cool, and tried to fix them with my (mediocre, as I mostly do rust) knowledge.

I get it now, super sorry mate.

**Comment by arithefirst** [comment]
It's ok, just for future reference, being a dick to people is not a great way to get PRs merged

**Comment by redactedontop** [comment]
I don't think I was a dick for saying "I'm losing my patience", but to each their own.

Sorry, mate.

**Pull request closed without merging**
